# Generated by Django 4.0 on 2022-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_week', models.CharField(max_length=2)),
                ('day_active', models.BooleanField()),
                ('duration_time', models.TimeField(verbose_name='%H:%M')),
                ('begin_time', models.TimeField(verbose_name='%H:%M')),
                ('end_time', models.TimeField(verbose_name='%H:%M')),
                ('visits', models.CharField(max_length=5)),
            ],
        ),
    ]
